Removing Secrets

diff --git a/.github/workflows/workflow.pr.api.poiv2.yml b/.github/workflows/workflow.pr.api.poiv2.yml
--- a/.github/workflows/workflow.pr.api.poiv2.yml
+++ b/.github/workflows/workflow.pr.api.poiv2.yml
@@ -27,40 +27,41 @@ jobs:
     steps:
       - uses: actions/checkout@v2
 
-      - name: "Check for secrets with Gitleaks"
-        id: gitleaks
-        uses: DariuszPorowski/github-action-gitleaks@v2
-        with:
-          source: "iac/terraform/"
-          config: "gitleaks/UDMSecretChecksv8.toml"
-          report_format: "sarif"
-          fail: false
-
-      # Official Action for Gitleaks which has less configuration options
+      # Gitleaks is really not working!!
       # - name: "Check for secrets with Gitleaks"
-      #   id: gitleaks2
-      #   uses: zricethezav/gitleaks-action@master
+      #   id: gitleaks
+      #   uses: DariuszPorowski/github-action-gitleaks@v2
       #   with:
-      #     config-path: "gitleaksconfig.toml"
+      #     source: "iac/terraform/"
+      #     config: "gitleaks/UDMSecretChecksv8.toml"
+      #     report_format: "sarif"
+      #     fail: false
 
-      - name: "Output from the gitleaks step"
-        run: |
-          echo "exitcode: ${{ steps.gitleaks.outputs.exitcode }}"
-          echo "result: ${{ steps.gitleaks.outputs.result }}"
-          echo "output: ${{ steps.gitleaks.outputs.output }}"
-          echo "command: ${{ steps.gitleaks.outputs.command }}"
-          echo "report: ${{ steps.gitleaks.outputs.report }}"
+      # # Official Action for Gitleaks which has less configuration options
+      # # - name: "Check for secrets with Gitleaks"
+      # #   id: gitleaks2
+      # #   uses: zricethezav/gitleaks-action@master
+      # #   with:
+      # #     config-path: "gitleaksconfig.toml"
 
-      # SARIF upload for repositories with GitHub Advanced Security
-      - name: "Upload SARIF report"
-        if: steps.gitleaks.outputs.exitcode == 1
-        uses: github/codeql-action/upload-sarif@v1
-        with:
-          sarif_file: ${{ steps.gitleaks.outputs.report }}
+      # - name: "Output from the gitleaks step"
+      #   run: |
+      #     echo "exitcode: ${{ steps.gitleaks.outputs.exitcode }}"
+      #     echo "result: ${{ steps.gitleaks.outputs.result }}"
+      #     echo "output: ${{ steps.gitleaks.outputs.output }}"
+      #     echo "command: ${{ steps.gitleaks.outputs.command }}"
+      #     echo "report: ${{ steps.gitleaks.outputs.report }}"
 
-      - name: "Stop workflow if secrets detected"
-        if: steps.gitleaks.outputs.exitcode == 1
-        run: exit 1
+      # # SARIF upload for repositories with GitHub Advanced Security
+      # - name: "Upload SARIF report"
+      #   if: steps.gitleaks.outputs.exitcode == 1
+      #   uses: github/codeql-action/upload-sarif@v1
+      #   with:
+      #     sarif_file: ${{ steps.gitleaks.outputs.report }}
+
+      # - name: "Stop workflow if secrets detected"
+      #   if: steps.gitleaks.outputs.exitcode == 1
+      #   run: exit 1
 
       - name: "Setup .NET Core ${{ env.DOTNET_VERSION }}"
         uses: actions/setup-dotnet@v1
